source 'http://rubygems.org'

gem 'rails', '3.0.3'
gem 'sqlite3-ruby', :require => 'sqlite3'

group :test, :development do
  gem "rspec-rails"
end

group :test do
  gem "webrat"
  gem "rspec"
  gem "cucumber-rails"
  gem "database_cleaner"
  gem "capybara"
end
